version: '3.3'

services:
   php-micro:
     container_name: php-micro
     build: 
       context: ./php
     restart: always
     volumes:
       - type: bind
         source: ./repos
         target: /app/repos

   apache-micro:
     container_name: apache-micro
     image: httpd:2.4-alpine
     ports:       
       - 80:80 
     restart: always
     volumes:
       - type: bind
         source: ./repos
         target: /app/repos
       - type: bind
         source: ./apache/httpd.conf
         target: /usr/local/apache2/conf/httpd.conf

   db-micro:
     container_name: db-micro
     image: mysql:5.7
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: practices
       MYSQL_USER: root
       MYSQL_PASSWORD: root
     volumes:
       - type: volume
         source: db_persistent_data
         target: /var/lib/mysql
         volume:
          nocopy: true

volumes:
    db_persistent_data:
      driver: local